version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    depends_on:
      - db
  nuxt-app:
    build:
      context: ./nuxt-app
    ports:
      - '8080:3000'
    depends_on:
      - api
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
