version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    depends_on:
      - db
  nuxt-app:
    build:
      context: ./nuxt-app
    ports:
      - '8080:3000'
    depends_on:
      - api
    networks:
      - ambiente_dev
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_dev
      MYSQL_USER: user_database
      MYSQL_PASSWORD: 123456
    ports:
      - '3366:3306'
    networks:
      - ambiente_dev


networks:
  ambiente_dev:
    driver: bridge

